# Generated by Django 4.2.1 on 2023-06-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_bloguser_interests_bloguser_profession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
